### ISSUE TITLE
passer puissance 4 en full JSON

### ISSUE THREAD

**Issue by gnieark** [gnieark/botsArena#56]

**Comment by moul** [comment]
ping moi quand t'as fini que je check si le proto est iso avec le nouveau format :)

**Comment by gnieark** [comment]
ok, je le ferai ;) , Merci d'avance à toi de donner un bot à manger à Botsarena.

j'ai commencé le passage en full JSON, donc ce soir ou demain ou max après demain ce sera fait

**Comment by gnieark** [comment]
ping @moul tu peux test sur le script de test http://botsarena-dev.tinad.fr/testBotScripts/connectfour.html (id plop mdp plip)

Je n'ai pas encore fait tous les tests unitaires sur l'arène par contre, et je n'ai pas mis à jour les specs.

**Comment by gnieark** [comment]
done (reste à traduire les nouvelles specs en anglais)
https://github.com/gnieark/botsArena/pull/64
